# Generated by Django 6.0.7 on 2026-07-17 07:49

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='booking.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='booking.location')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.CharField(max_length=5)),
                ('coach', models.CharField(max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=44)),
                ('fare', models.PositiveIntegerField(help_text='Fare per seat, in KES')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.route')),
            ],
            options={
                'ordering': ['route', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=booking.models.generate_reference, editable=False, max_length=12, unique=True)),
                ('travel_date', models.DateField()),
                ('seats', models.JSONField(help_text='List of seat numbers, e.g. [3, 4]')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_id_number', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('total_fare', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dropoff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='booking.location')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='booking.location')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
